version: "3.9"

services:
  egochallenge-api:
    build: .
    container_name: egochallenge-api
    # Public environment
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=pgdb
    # Opening ports
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    # Load ENV variables in container
    env_file:
      - .env
    # Makes directory sync from container to drive
    volumes:
      - .:/app

  pgdb:
    image: postgres:13
    container_name: pgdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5433"
volumes:
  postgres_data:
